### ISSUE TITLE
kramdown-rfc-cache-subseries-bibxml requires net-http-persistent

### ISSUE THREAD

**Issue by mcr** [cabo/kramdown-rfc2629#127]
This dependancy is not mentioned in the Gemfile, so I get:

~~~~
dooku-[~](2.6.6) mcr 10003 %kramdown-rfc-cache-subseries-bibxml
Traceback (most recent call last):
        6: from /usr/local/rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `<main>'
        5: from /usr/local/rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `eval'
        4: from /usr/local/rvm/gems/ruby-2.6.6/bin/kramdown-rfc-cache-subseries-bibxml:23:in `<main>'
        3: from /usr/local/rvm/gems/ruby-2.6.6/bin/kramdown-rfc-cache-subseries-bibxml:23:in `load'
        2: from /usr/local/rvm/gems/ruby-2.6.6/gems/kramdown-rfc2629-1.4.17/bin/kramdown-rfc-cache-subseries-bibxml:16:in `<top (required)>'
        1: from /usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- net/http/persistent (LoadError)
~~~~

install manually with:

~~~~
dooku-[~](2.6.6) mcr 10005 %gem install net-http-persistent
~~~~

**Comment by cabo** [comment]
It certainly needs a better error message.
(The unfortunate reason why net-http-persistent is not a dependency is discussed in #101 .)
