### ISSUE TITLE
empty contributor section results in error

### ISSUE THREAD

**Issue by mcr** [cabo/kramdown-rfc2629#129]
<pre>
dooku-[lwork/lamps/rfc7030est-csrattrs-clarifications](2.6.6) mcr 10108 %make
kramdown-rfc2629 -3 lamps-rfc7030-csrattrs.mkd >lamps-rfc7030-csrattrs.xml
Traceback (most recent call last):
	14: from /usr/local/rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:22:in `<main>'
	13: from /usr/local/rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:22:in `eval'
	12: from /usr/local/rvm/gems/ruby-2.6.6/bin/kramdown-rfc2629:23:in `<main>'
	11: from /usr/local/rvm/gems/ruby-2.6.6/bin/kramdown-rfc2629:23:in `load'
	10: from /usr/local/rvm/gems/ruby-2.6.6/gems/kramdown-rfc2629-1.5.6/bin/kramdown-rfc2629:497:in `<top (required)>'
	 9: from /usr/local/rvm/gems/ruby-2.6.6/gems/kramdown-rfc2629-1.5.6/bin/kramdown-rfc2629:360:in `xml_from_sections'
	 8: from /usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/erb.rb:901:in `result'
	 7: from /usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/erb.rb:901:in `eval'
	 6: from (erb):118:in `xml_from_sections'
	 5: from /usr/local/rvm/gems/ruby-2.6.6/gems/kramdown-rfc2629-1.5.6/lib/kramdown-rfc/parameterset.rb:50:in `arr'
	 4: from /usr/local/rvm/gems/ruby-2.6.6/gems/kramdown-rfc2629-1.5.6/lib/kramdown-rfc/parameterset.rb:50:in `each'
	 3: from (erb):119:in `block in xml_from_sections'
	 2: from /usr/local/rvm/gems/ruby-2.6.6/gems/kramdown-rfc2629-1.5.6/lib/kramdown-rfc/refxml.rb:44:in `authorps_from_hash'
	 1: from /usr/local/rvm/gems/ruby-2.6.6/gems/kramdown-rfc2629-1.5.6/lib/kramdown-rfc/refxml.rb:44:in `new'
/usr/local/rvm/gems/ruby-2.6.6/gems/kramdown-rfc2629-1.5.6/lib/kramdown-rfc/parameterset.rb:8:in `initialize': *** invalid parameter set nil (RuntimeError)
make: *** [Makefile:10: lamps-rfc7030-csrattrs.xml] Error 1
[1]    1024172 exit 2     make
dooku-[lwork/lamps/rfc7030est-csratt
</pre>

**Comment by mcr** [comment]
This was the result of having:

<pre>
contributor:
   -
</pre>

which might well be an error, but it took me awhile to figure out where the problem was.
