### ISSUE TITLE
Error generating XML from example file

### ISSUE THREAD

**Issue by kesara** [cabo/kramdown-rfc2629#150]
kramdown-rfc2629 version: `1.5.19`

I tried generating XML from [draft-ietf-core-block-xx.mkd](https://github.com/cabo/kramdown-rfc2629/blob/master/examples/draft-ietf-core-block-xx.mkd) in examples.
That produces the following error:
```
$ kramdown-rfc2629 draft-ietf-core-block-xx.mkd
/Users/kesara/.rvm/gems/ruby-3.0.0/gems/kramdown-rfc2629-1.5.19/lib/kramdown-rfc/parameterset.rb:32:in `attr': undefined method `intern' for nil:NilClass (NoMethodError)
	from /Users/kesara/.rvm/gems/ruby-3.0.0/gems/kramdown-rfc2629-1.5.19/lib/kramdown-rfc/parameterset.rb:36:in `block in attrs'
	from /Users/kesara/.rvm/gems/ruby-3.0.0/gems/kramdown-rfc2629-1.5.19/lib/kramdown-rfc/parameterset.rb:36:in `map'
	from /Users/kesara/.rvm/gems/ruby-3.0.0/gems/kramdown-rfc2629-1.5.19/lib/kramdown-rfc/parameterset.rb:36:in `attrs'
	from (erb):2:in `person_element_from_aups'
	from /Users/kesara/.rvm/gems/ruby-3.0.0/gems/erb-2.2.3/lib/erb.rb:905:in `eval'
	from /Users/kesara/.rvm/gems/ruby-3.0.0/gems/erb-2.2.3/lib/erb.rb:905:in `result'
	from /Users/kesara/.rvm/gems/ruby-3.0.0/gems/kramdown-rfc2629-1.5.19/lib/kramdown-rfc/refxml.rb:100:in `person_element_from_aups'
	from (erb):51:in `block in xml_from_sections'
	from /Users/kesara/.rvm/gems/ruby-3.0.0/gems/kramdown-rfc2629-1.5.19/lib/kramdown-rfc/parameterset.rb:56:in `each'
	from /Users/kesara/.rvm/gems/ruby-3.0.0/gems/kramdown-rfc2629-1.5.19/lib/kramdown-rfc/parameterset.rb:56:in `arr'
	from (erb):48:in `xml_from_sections'
	from /Users/kesara/.rvm/gems/ruby-3.0.0/gems/erb-2.2.3/lib/erb.rb:905:in `eval'
	from /Users/kesara/.rvm/gems/ruby-3.0.0/gems/erb-2.2.3/lib/erb.rb:905:in `result'
	from /Users/kesara/.rvm/gems/ruby-3.0.0/gems/kramdown-rfc2629-1.5.19/bin/kramdown-rfc2629:360:in `xml_from_sections'
	from /Users/kesara/.rvm/gems/ruby-3.0.0/gems/kramdown-rfc2629-1.5.19/bin/kramdown-rfc2629:497:in `<top (required)>'
	from /Users/kesara/.rvm/gems/ruby-3.0.0/bin/kramdown-rfc2629:23:in `load'
	from /Users/kesara/.rvm/gems/ruby-3.0.0/bin/kramdown-rfc2629:23:in `<main>'
```

**Comment by cabo** [comment]
Thank you!
