### ISSUE TITLE
problem with redirect

### ISSUE THREAD

**Issue by boutil** [cabo/kramdown-rfc2629#27]
Hi,

when trying to run the "stupid" example, I encounter the following problem. It was working before. Is it related with a change on the ietf.org website? Does it have to be reflected somewhere in the code of kramdown-rfc2629?

```
ruby -I ../lib/ ../bin/kramdown-rfc2629 stupid.mkd stupid.xml 
.refcache/reference.RFC.2119.xml: fetching
/usr/lib/ruby/2.3.0/open-uri.rb:225:in `open_loop': redirection forbidden: http://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml -> https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml (RuntimeError)
        from /usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
        from /usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
        from /usr/lib/ruby/2.3.0/open-uri.rb:35:in `open'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:436:in `block in get_and_cache_resource'
        from /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
        from /usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
        from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
        from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
        from /usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:435:in `get_and_cache_resource'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:487:in `block in convert_img'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:482:in `scan'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:482:in `convert_img'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:125:in `block in inner_a'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:123:in `map'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:123:in `inner_a'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:130:in `inner'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:143:in `convert_p'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:125:in `block in inner_a'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:123:in `map'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:123:in `inner_a'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:130:in `inner'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:615:in `convert_root'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:118:in `convert1'
        from /home/boutil/src/ruby/kramdown-rfc2629/lib/kramdown-rfc2629.rb:113:in `convert'
        from /usr/lib/ruby/vendor_ruby/kramdown/converter/base.rb:105:in `convert'
        from /usr/lib/ruby/vendor_ruby/kramdown/document.rb:120:in `method_missing'
        from ../bin/kramdown-rfc2629:341:in `<main>'
```

**Comment by cabo** [comment]
Hi Cédric,

Indeed, there is discussion today on the tools mailing list about a redirection problem, exacerbated by a certificate problem. I have to think about ways of making kramdown-rfc more robust to this kind of situation.  

Grüße, Carsten

**Comment by cabo** [comment]
This appears to be a bug in the open-uri library, though.

Workaround at the moment:

XML_RESOURCE_ORG_PREFIX=https://xml2rfc.tools.ietf.org/public/rfc
kramdown-rfc2629

(i.e., set the environment variable XML_RESOURCE_ORG_PREFIX to the value
https://xml2rfc.tools.ietf.org/public/rfc before calling kramdown-rfc2629)

Grüße, Carsten


Carsten Bormann wrote:

**Comment by cabo** [comment]
I pushed a 1.0.34 with a workaround installed.  Please update:

`gem update`

**Comment by cabo** [comment]
Leaving this open, as the workaround still needs to be moved to the proper stable base URI.

**Comment by jaimejim** [comment]
I can confirm that `gem update` to kramdown-rfc2629-1.0.34.gem fixes the bug for me.

**Comment by boutil** [comment]
I tried 1.0.36, and the problem is fixed for me too. Thanks!

**Comment by josephlhall** [comment]
Heya, after updating to a newer kramdown-rfc2629 I get a message "Occasionally run `certified-update`" but I had to hunt around to figure out that was the executable provided by the following gem: https://github.com/stevegraham/certified

Would be good to make that a bit easier to figure out.
