### ISSUE TITLE
Can't get plantuml or mermaid to work

### ISSUE THREAD

**Issue by larseggert** [cabo/kramdown-rfc2629#98]
Am trying to put a docker image together that would always have the latest versions of all the tools that make up the I-D toolchain installed: https://github.com/larseggert/i-d-toolchain

As part of that, I made a short I-D that tries to execute all the different tools: https://github.com/larseggert/i-d-toolchain/blob/main/draft-i-d-toolchain-test.md

However, the `plantuml` and `mermaid` tests fail, and I don't know why?

The `~~ plantuml` case fails with:
```
Traceback (most recent call last):
	14: from /usr/bin/kramdown-rfc2629:23:in `<main>'
	13: from /usr/bin/kramdown-rfc2629:23:in `load'
	12: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/bin/kramdown-rfc2629:398:in `<top (required)>'
	11: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-1.17.0/lib/kramdown/document.rb:117:in `method_missing'
	10: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-1.17.0/lib/kramdown/converter/base.rb:105:in `convert'
	 9: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:196:in `convert'
	 8: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:201:in `convert1'
	 7: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:957:in `convert_root'
	 6: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:213:in `inner'
	 5: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:206:in `inner_a'
	 4: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:206:in `map'
	 3: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:208:in `block in inner_a'
	 2: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:400:in `convert_codeblock'
	 1: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:301:in `memoize'
/usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:301:in `binread': No such file or directory @ rb_sysopen - .refcache/kdrfc-1_3_27-svg_tool_process-21c1b1b1e90827853ec99d7cc9cd3546ef018348.cache (Errno::ENOENT)
	16: from /usr/bin/kramdown-rfc2629:23:in `<main>'
	15: from /usr/bin/kramdown-rfc2629:23:in `load'
	14: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/bin/kramdown-rfc2629:398:in `<top (required)>'
	13: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-1.17.0/lib/kramdown/document.rb:117:in `method_missing'
	12: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-1.17.0/lib/kramdown/converter/base.rb:105:in `convert'
	11: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:196:in `convert'
	10: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:201:in `convert1'
	 9: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:957:in `convert_root'
	 8: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:213:in `inner'
	 7: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:206:in `inner_a'
	 6: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:206:in `map'
	 5: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:208:in `block in inner_a'
	 4: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:400:in `convert_codeblock'
	 3: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:300:in `memoize'
	 2: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:304:in `rescue in memoize'
	 1: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:304:in `call'
/usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:339:in `svg_tool_process': no implicit conversion of nil into String (TypeError)
```

The `~~~ mermaid` case fails with:
```
Traceback (most recent call last):
	14: from /usr/bin/kramdown-rfc2629:23:in `<main>'
	13: from /usr/bin/kramdown-rfc2629:23:in `load'
	12: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/bin/kramdown-rfc2629:398:in `<top (required)>'
	11: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-1.17.0/lib/kramdown/document.rb:117:in `method_missing'
	10: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-1.17.0/lib/kramdown/converter/base.rb:105:in `convert'
	 9: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:196:in `convert'
	 8: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:201:in `convert1'
	 7: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:957:in `convert_root'
	 6: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:213:in `inner'
	 5: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:206:in `inner_a'
	 4: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:206:in `map'
	 3: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:208:in `block in inner_a'
	 2: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:400:in `convert_codeblock'
	 1: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:301:in `memoize'
/usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:301:in `binread': No such file or directory @ rb_sysopen - .refcache/kdrfc-1_3_27-svg_tool_process-fcda95417cbfb32c1f0fd75d8e46709ece053d16.cache (Errno::ENOENT)
	17: from /usr/bin/kramdown-rfc2629:23:in `<main>'
	16: from /usr/bin/kramdown-rfc2629:23:in `load'
	15: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/bin/kramdown-rfc2629:398:in `<top (required)>'
	14: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-1.17.0/lib/kramdown/document.rb:117:in `method_missing'
	13: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-1.17.0/lib/kramdown/converter/base.rb:105:in `convert'
	12: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:196:in `convert'
	11: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:201:in `convert1'
	10: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:957:in `convert_root'
	 9: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:213:in `inner'
	 8: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:206:in `inner_a'
	 7: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:206:in `map'
	 6: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:208:in `block in inner_a'
	 5: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:400:in `convert_codeblock'
	 4: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:300:in `memoize'
	 3: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:304:in `rescue in memoize'
	 2: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:304:in `call'
	 1: from /usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:333:in `svg_tool_process'
/usr/lib/ruby/gems/2.7.0/gems/kramdown-rfc2629-1.3.27/lib/kramdown-rfc2629.rb:333:in `read': No such file or directory @ rb_sysopen - /tmp/kramdown-rfc20210205-9-1cclenh.svg (Errno::ENOENT)
```

**Comment by cabo** [comment]
I need to improve those error messages :-)
@startuml and @enduml are added by kramdown-rfc, you need to leave these out (once I have fixed a bug in the plantuml processing; to be fixed in 1.3.27; workaround: use plantuml-utxt).

The remaining problem I get is

```
draft-i-d-toolchain-test.xml(334): Error: Invalid attribute rx for element polygon, at /rfc/middle/section[7]/artset/artwork[1]/*/*/*/*[4]/*[3]/*[1]
/Users/cabo/id/draft-i-d-toolchain-test.xml(13): Error: Invalid document before running preptool.
Unable to complete processing draft-i-d-toolchain-test.xml
```
which is some mermaid output I don't understand.

**Comment by larseggert** [comment]
I think I got it working now, thanks!

**Comment by cabo** [comment]
So is there anything that the SVG smoother needs to do to handle the mermaid case?

**Comment by larseggert** [comment]
It seems to just work with the current version of my testcase I-D. But mermaid is completely nuts in terms of dependencies, it requires Chromium for example.
